spring:
  application:
    name: Cloud-Security
  datasource:
    url: jdbc:postgresql://localhost:5432/CloudStorage
    username: postgres
    password: mfcj43ow
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

app:
  jwt:
    secret: super_secret_important_key_which_is_also_very_long_and_secure
    expiration-ms: 86400000